// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using restauranteBD.Data;

#nullable disable

namespace restauranteBD.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_categoria");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCategoria"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<int?>("IdDestino")
                        .HasColumnType("integer")
                        .HasColumnName("id_destino");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Tipo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo");

                    b.HasKey("IdCategoria");

                    b.HasIndex("IdDestino");

                    b.ToTable("categorias");
                });

            modelBuilder.Entity("Comanda", b =>
                {
                    b.Property<int>("IdComanda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_comanda");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdComanda"));

                    b.Property<string>("EstadoCocina")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("pendiente")
                        .HasColumnName("estado_cocina");

                    b.Property<string>("EstadoPago")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("por_cobrar")
                        .HasColumnName("estado_pago");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_apertura");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_cierre");

                    b.Property<int?>("IdCuenta")
                        .HasColumnType("integer")
                        .HasColumnName("id_cuenta");

                    b.Property<int?>("IdMesa")
                        .HasColumnType("integer")
                        .HasColumnName("id_mesa");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre_cliente");

                    b.HasKey("IdComanda");

                    b.HasIndex("EstadoCocina");

                    b.HasIndex("EstadoPago");

                    b.HasIndex("IdCuenta");

                    b.HasIndex("IdMesa")
                        .HasFilter("estado_pago != 'pagada'");

                    b.HasIndex("IdUsuario");

                    b.ToTable("comandas");
                });

            modelBuilder.Entity("Destino", b =>
                {
                    b.Property<int>("IdDestino")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_destino");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDestino"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdDestino");

                    b.ToTable("destinos");
                });

            modelBuilder.Entity("DetalleComanda", b =>
                {
                    b.Property<int>("IdDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_detalle");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDetalle"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<string>("EstadoItem")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("pendiente")
                        .HasColumnName("estado_item");

                    b.Property<int>("IdComanda")
                        .HasColumnType("integer")
                        .HasColumnName("id_comanda");

                    b.Property<int>("IdProducto")
                        .HasColumnType("integer")
                        .HasColumnName("id_producto");

                    b.Property<string>("Notas")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("notas");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio_unitario");

                    b.HasKey("IdDetalle");

                    b.HasIndex("EstadoItem");

                    b.HasIndex("IdComanda");

                    b.HasIndex("IdProducto");

                    b.ToTable("detalle_comanda");
                });

            modelBuilder.Entity("Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_producto");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProducto"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<decimal?>("CostoEstimado")
                        .HasColumnType("numeric")
                        .HasColumnName("costo_estimado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("integer")
                        .HasColumnName("id_categoria");

                    b.Property<decimal?>("MargenGanancia")
                        .HasColumnType("numeric")
                        .HasColumnName("margen_ganancia");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdProducto");

                    b.HasIndex("IdCategoria");

                    b.ToTable("productos");
                });

            modelBuilder.Entity("restauranteBD.Models.Cuenta", b =>
                {
                    b.Property<int>("IdCuenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCuenta"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("IdMesa")
                        .HasColumnType("integer");

                    b.HasKey("IdCuenta");

                    b.ToTable("Cuentas");
                });

            modelBuilder.Entity("restauranteBD.Models.Mesa", b =>
                {
                    b.Property<int>("IdMesa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_mesa")
                        .HasAnnotation("Relational:JsonPropertyName", "idMesa");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMesa"));

                    b.Property<bool>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activa");

                    b.Property<int?>("Capacidad")
                        .HasColumnType("integer")
                        .HasColumnName("capacidad");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.Property<string>("Tipo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.HasKey("IdMesa");

                    b.HasIndex("Activa");

                    b.ToTable("mesas");

                    b.HasData(
                        new
                        {
                            IdMesa = 1,
                            Activa = true,
                            Capacidad = 4,
                            Nombre = "M1",
                            Tipo = "interior"
                        },
                        new
                        {
                            IdMesa = 2,
                            Activa = true,
                            Capacidad = 4,
                            Nombre = "M2",
                            Tipo = "interior"
                        },
                        new
                        {
                            IdMesa = 3,
                            Activa = true,
                            Capacidad = 6,
                            Nombre = "M3",
                            Tipo = "terraza"
                        },
                        new
                        {
                            IdMesa = 4,
                            Activa = true,
                            Capacidad = 2,
                            Nombre = "M4",
                            Tipo = "terraza"
                        },
                        new
                        {
                            IdMesa = 5,
                            Activa = true,
                            Capacidad = 8,
                            Nombre = "Barra",
                            Tipo = "barra"
                        });
                });

            modelBuilder.Entity("restauranteBD.Models.ProductoPresentacion", b =>
                {
                    b.Property<int>("IdPresentacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_presentacion");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPresentacion"));

                    b.Property<int>("IdProducto")
                        .HasColumnType("integer")
                        .HasColumnName("id_producto");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre_presentacion");

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric")
                        .HasColumnName("precio");

                    b.HasKey("IdPresentacion");

                    b.HasIndex("IdProducto");

                    b.ToTable("producto_presentaciones");
                });

            modelBuilder.Entity("restauranteBD.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_rol");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("IdRol");

                    b.ToTable("roles", "public");
                });

            modelBuilder.Entity("restauranteBD.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<int>("IdRol")
                        .HasColumnType("integer")
                        .HasColumnName("id_rol");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdRol");

                    b.ToTable("usuarios", "public");
                });

            modelBuilder.Entity("Categoria", b =>
                {
                    b.HasOne("Destino", "Destino")
                        .WithMany("Categorias")
                        .HasForeignKey("IdDestino");

                    b.Navigation("Destino");
                });

            modelBuilder.Entity("Comanda", b =>
                {
                    b.HasOne("restauranteBD.Models.Cuenta", "Cuenta")
                        .WithMany("Comandas")
                        .HasForeignKey("IdCuenta");

                    b.HasOne("restauranteBD.Models.Mesa", "Mesa")
                        .WithMany("Comandas")
                        .HasForeignKey("IdMesa")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("restauranteBD.Models.Usuario", "Usuario")
                        .WithMany("Comandas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cuenta");

                    b.Navigation("Mesa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DetalleComanda", b =>
                {
                    b.HasOne("Comanda", "Comanda")
                        .WithMany("Detalles")
                        .HasForeignKey("IdComanda")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Producto", "Producto")
                        .WithMany("DetalleComandas")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comanda");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Producto", b =>
                {
                    b.HasOne("Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("restauranteBD.Models.ProductoPresentacion", b =>
                {
                    b.HasOne("Producto", "Producto")
                        .WithMany("Presentaciones")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("restauranteBD.Models.Usuario", b =>
                {
                    b.HasOne("restauranteBD.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Comanda", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Destino", b =>
                {
                    b.Navigation("Categorias");
                });

            modelBuilder.Entity("Producto", b =>
                {
                    b.Navigation("DetalleComandas");

                    b.Navigation("Presentaciones");
                });

            modelBuilder.Entity("restauranteBD.Models.Cuenta", b =>
                {
                    b.Navigation("Comandas");
                });

            modelBuilder.Entity("restauranteBD.Models.Mesa", b =>
                {
                    b.Navigation("Comandas");
                });

            modelBuilder.Entity("restauranteBD.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("restauranteBD.Models.Usuario", b =>
                {
                    b.Navigation("Comandas");
                });
#pragma warning restore 612, 618
        }
    }
}
